apiVersion: v1
kind: Pod
metadata:
  name: telnet
  namespace: default
spec:
  containers:
  - image: aslom/telnet
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: telnet
  restartPolicy: Always
