apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: knative-eventing
spec:
  containers:
  - image: aslom/kafka-cli
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: kafka-cli
  restartPolicy: Always
