apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli2
  namespace: default
spec:
  containers:
  - image: aslom/kafka-cli
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: kafka-cli
    volumeMounts:
        - name: kafka-secret2-vol
          mountPath: /opt/config
          readOnly: true
  restartPolicy: Always
  volumes:
      - name: kafka-secret2-vol
        secret:
          secretName: kafka-secret2
